title: "The Black Box"
description: "Atlas Exchange — Editorial Intelligence"
url: "https://blog.success.justgoatlas.com"
baseurl: ""

logo: "/assets/images/favicon.png"
favicon: "/favicon.png"
masthead_title: "The Black Box"

remote_theme: "mmistakes/minimal-mistakes@4.28.0"
minimal_mistakes_skin: "dark"

markdown: kramdown
highlighter: rouge

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-include-cache

# Author Profile
author:
  name: "Dion Gamble"
  avatar: "/assets/images/headshot2.jpg"
  bio: "Writer, listener and navigator."
  location: "United States Eastern"
  links:
    - label: "email"
      icon: "fas fa-fw fa-envelope"
      url: "mailto:"dion@justgoatlas.com"

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      author_profile: true
      layout: single
      read_time: true
      comments: false
      share: false
    
  - scope:
      path: ""
      type: "pages"
    values:
      author_profile: true

# Permalinks
permalink: /:categories/:title/

# Collections (optional but clean)
collections:
  posts:
    output: true

# Build settings
include:
  - _pages

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
skip_links: false

paginate: 5
paginate_path: "/page:num/"

